Question: Fragen
Answer: Antwort
Nr: Nr
Exams: Klausuren
IsCorrect: Ist es korrekt?
SubmitExam: Klausur absenden
StartExam: Starte Klausurerstellung
ExamTitle: Klausurname
PassPercentage: Prozent zum Bestehen
QuestionNum: Anzahl der Fragen
ShowXML: Zeige XML
DelExam: Lösche Klausur
ConfirmDelExam: Möchten sie die Klausur wirklich löschen?
ConfirmDelExam2: Bitte schreibe sie den Klausurnamen in das Feld und bestätigen mit Löschen.
TitleMisMatch: Tut mir leid, ihre Eingabe stimmt nicht mit dem Klausurnamen überein.
SuccessDelete title@Text: Sie haben erfolgreich die Klausur #{title} gelöscht.
GetBack: Zurück!