Question: Question
Answer count@Int: #{plural count "Answer" "Answers"}
Nr: Nr
Exams: Exams
IsCorrect: Is it correct?
SubmitExam: Submit exam
StartExam: Start exam creation
ExamTitle: Exam title
PassPercentage: Passing percentage
QuestionNum: Number of questions
ShowXML: Show XML
DelExam: Delete exam
ConfirmDelExam: Do you really want to delete this exam?
ConfirmDelExam2: Please type the examtitle correctly and click delete.
TitleMisMatch: Sorry, the input does not match the title.
SuccessDelete title@Text: You successfully deleted #{title}.
GetBack: Get back!

FileRec fInfo@Text: File recieved: #{fInfo}.
ErrInXML_P1: Error occured, please check if it is a
ErrInXML_P2: valid xml file.
ChooseXML: Please choose a xml file to upload.
Upload: Upload
SubmitQuest count@Int: Submit #{plural count "question" "questions"}
InputNeg: Sorry, this input can't be negative!
PassedExam: Congratulations, you passed the test!
NoPassExam: Sorry, you didn't pass.
Evaluate: Evaluate
Points: Points

#Question short
Q: Q