Default: &defaults
  database: quiz.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: quiz_test.sqlite3
  <<: *defaults

Staging:
  database: quiz_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: quiz_production.sqlite3
  poolsize: 100
  <<: *defaults
